version: "3"
services:
  postgres:
    container_name: postgres
    build:
      # context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vector
  nemollm-embedding:
    container_name: nemo-retriever-embedding-microservice
    image: nvcr.io/ohlfw0olaadg/ea-participants/nemo-retriever-embedding-microservice:24.04
    volumes:
    - /opt/data/nv-embed-qa_v4:/model-checkpoint-path
    command:  bin/web -p 9080 -c /model-checkpoint-path/NV-Embed-QA-4.nemo -g model_config_templates/NV-Embed-QA_template.yaml
    ports:
    - "9080:9080"
    expose:
    - "9080"
    shm_size: 8gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${EMBEDDING_MS_GPU_ID:-0}']
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/v1/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10m
volumes:
  postgres_data:
